### ISSUE TITLE
event not supported

### ISSUE THREAD

**Issue by purvid0204** [Latitude-Financial/magento2-latitudepay-genoapay#43]
Hello,

'payment_method_is_active' is event is supported on checkout page.i want to disable/enable payment method using event but in observer i do not get 'latitudepay' payment method.

Please reply as early as possible.

**Comment by william-lfs** [comment]
Hi Purvi,

It looks like you are trying to programmatically disable/enable LatitudePay payment method on checkout using a custom module/script.
I am afraid we are not able to help you much on this as this is not part of our plugin feature.
Our plugin is meant to be enabled/disabled from Magento 2 backend via UI only.

Further customisation to your site as to what you are trying to achieve here is the responsibility of the developers making the custom module/script.

Please ensure that the total checkout value is => $20 as our LatitudePay payment method will not appear on checkout if the amount is less than $20.

We also replied to your Zendesk ticket # 1835510.

Thank you.

Regards,
William
